# the license below only applies to this file
#
# MIT License
#
# Copyright -- PowerDNS.COM B.V. and its contributors
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

name: 'choose Ubuntu mirror for PowerDNS builds in Github Actions'
inputs:
  apt-repository:
    description: 'Default Ubuntu APT repository mirror'
    required: true
    default: 'mirror.leaseweb.net'
runs:
  using: "composite"
  steps:
    #- run: echo not changing mirror, using default Azure mirror
    #  shell: bash
    - run: sudo sed -i 's/azure\.archive\.ubuntu\.com/${{ inputs.apt-repository }}/' /etc/apt/sources.list
      shell: bash
    - run: "echo -e 'Package: *odbc*\nPin: origin \"${{ inputs.apt-repository }}\"\nPin-Priority: 1001' | sudo tee /etc/apt/preferences"
      shell: bash
